### ISSUE TITLE
Not working for non-GitHub file?

### ISSUE THREAD

**Issue by Naereen** [ngryman/badge-size#58]
Hi,
I wanted to use a badge for [this .zip file on a Github release](https://github.com/Naereen/kaamelott-soundboard-desktop-app/releases/download/v0.1-alpha/kaamelott-soundboard-linux-x64.zip) and I cannot find a way to use your badge-size project.

http://img.badgesize.io/Naereen/kaamelott-soundboard-desktop-app/releases/download/v0.1-alpha/kaamelott-soundboard-linux-x64.zip.svg
http://img.badgesize.io/GitHub.com/Naereen/kaamelott-soundboard-desktop-app/releases/download/v0.1-alpha/kaamelott-soundboard-linux-x64.zip.svg
http://img.badgesize.io/http://GitHub.com/Naereen/kaamelott-soundboard-desktop-app/releases/download/v0.1-alpha/kaamelott-soundboard-linux-x64.zip.svg
http://img.badgesize.io/https://GitHub.com/Naereen/kaamelott-soundboard-desktop-app/releases/download/v0.1-alpha/kaamelott-soundboard-linux-x64.zip.svg

None seem to work for me.
I tried with another file, [this image](http://perso.crans.org/besson/_static/.besson.png) and it's also not working
http://img.badgesize.io/perso.crans.org/besson/_static/.besson.png.svg
http://img.badgesize.io/http://perso.crans.org/besson/_static/.besson.png.svg

Is there something I don't understand, or is it normal that it only works with GitHub file and relative URL? Thanks in advance :pray:

**Comment by ngryman** [comment]
Hey, `badgesize` should support any url if you specify the absolute url (like the second version of each of your urls).

To explain why it's not working for your release. Github forbids me to issue a `HEAD` request and returns a 403. It's probably for security reasons. But I have to say that the main purpose of `badgesize` is to advertise the size of plain text files for projects with a fast paced release cycle.
Please do not use it for big archives, I only have a free Heroku Dyno 😄. You could use a service like `shields.io` to create your badge and update it manually (or via a script your side).

For your image example, the server returns a 400. I'm not sure why though, but I have the feeling it's because it seems to be hosted on Github and you are using a custom DNS. Could you try with the raw url of the image (`raw.githubusercontent.com` or `github.io`)?

**Comment by Naereen** [comment]
Hi @ngryman, thanks for your quick answer.

I manually added the badge from `shields.io` with the size manually entered, it's way simpler. Cf. [this §](https://github.com/Naereen/kaamelott-soundboard-desktop-app#t%C3%A9l%C3%A9charger-lapplication-bureau-).

I understand about the limitation, no worries.

No issue for my example image. It's not hosted on GitHub, but no big deal.

Thanks anyway :+1:
