### ISSUE TITLE
Strip sourcemap comment before calculating size?

### ISSUE THREAD

**Issue by developit** [ngryman/badge-size#70]
Hi there!

Most people bundle their libraries using tools like Webpack, Parcel or Rollup. All of these remove sourcemap comments as part of the build process, meaning users of a library don't generally "pay" for sourcemap comments. For this reason, I've generally found it more logical to remove sourcemap comments prior to calculating compressed size.  Would you be open to stripping those comments out as part of badge-size?  In the past I've used `strip-json-comments` for this.  Cheers!

**Comment by styfle** [comment]
You might try bundlephobia such as [![](https://img.shields.io/bundlephobia/min/preact.svg)](https://img.shields.io/bundlephobia/min/preact.svg) and [![](https://img.shields.io/bundlephobia/minzip/preact.svg)](https://img.shields.io/bundlephobia/minzip/preact.svg)

**Comment by ngryman** [comment]
Hey @developit!

I like your proposition. But I deliberately try to keep this project as simple as possible. It has a clear contract, give it a URL, it will give you its content size. It is agnostic to the content, and not specialized to process specific file types.

I know that several tools like the one that @styfle linked above could work for you. But they also come with a maintenance cost (and a potential feature/bug proliferation) that I won't be able to sustain. I prefer a simple, focused project that will work forever.

That said, one solution I could bring to users with such use cases would be to write down recipes or examples. So I'm curious about your case, would it be possible for you to strip those comments and make the resulting file available at some URL? Or is it something that you can't do because you have some constraints?

**Comment by developit** [comment]
Potentially! That's a good idea.

**Comment by ngryman** [comment]
@developit Closing the issue. Tell me if you need something!
